### PR TITLE
Fix/storage event

### LINKED ISSUE #47: Strange behaviour on IE11
Hi,

I'm using the plugin to store a couple of simple values in local storage and it works all fine, except in IE (IE11), where there is no initial value set, and on changing (is a page size that I can change in an input) it gets in an infinite loop setting the variable to the new and initial value back and forth.

### PR DESCRIPTION
**Pull request by fsmanuel**
@MattNguyen can you review?

closes #47

### CODE REVIEW

File: tests/unit/local/settings-test.js [hunk 1]
```diff
@@ -50,7 +50,11 @@ test('it saves changes to localStorage', function(assert) {
 test('it updates when change events fire', function(assert) {
   assert.expect(3);
 
+  // setup testing
+  settings._testing = true;
```
Comment (MattNguyen) [inline tests/unit/local/settings-test.js]: Would it be better to set this in the `beforeEach` hook?

Comment (fsmanuel) [inline tests/unit/local/settings-test.js]: If we use it more frequently - yes. Right now it's more a hack ;)
