### PR TITLE
Fix importData

### LINKED ISSUE #233: #219 breaks importData
PR #219 breaks the importData function. The localstorage index is not updated until a browser refresh due to _indices on the adapter being set as a computed property(_indices does not reflect the current localstorage state). You can reproduce this by running the demo locally and trying to import a file like this [my-data.txt](https://github.com/funkensturm/ember-local-storage/files/794522/my-data.txt). Changing _indices back to a POJO fixes the issue, but will cause problems with tests as noted in the PR.

### PR DESCRIPTION
**Pull request by bendemboski**
PR #219 broke importData because importData was relying on the global-ness of the adapter index.

The fix is to remove an assumption that the import/export code was making that, while probably most of the time true, is incorrect. That assumption is that a single adapter instance is responsible for all model types, and that the adapter instance is a local storage adapter. If an application was using the session storage adapter, or was using the local storage adapter for some models and the session storage adapter for others, the import and export code would do the extremely wrong thing.

So, rather than make importData/exportData fundamentally functions of the adapter, they are now fundamentally functions of the store (via helper methods), and the store looks up the correct adapter for each model type in the data payload, ensuring that it gets/sends the data from/to the right place.

I left the importData/exportData methods on the adapters (via the mixin) to preserve backwards compatibility, in case anybody was accessing the functionality through the adapter instead of the store, but it just forwards to the same helpers as the store's importData/exportData.

Also, make sure unit tests are clearing session storage as well as local storage in case we write more session storage tests, and remove code that #219 made no-longer relevant (clearing out the adapter index before each test).

Fixes #233

### CODE REVIEW

**Comment by xn** [comment]
Any movement on this?

**Comment by fsmanuel** [comment]
@bendemboski Thanks a lot!

File: addon/helpers/import-export.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+  }, options || {});
+
+  let reloadTypes = [];
+
+  content = options.json ? JSON.parse(content) : content;
+
+  if (options.truncate) {
+    content.data.forEach((record) => {
+      const type = record.type;
+      const adapter = store.adapterFor(singularize(type));
```
Comment (fsmanuel) [inline addon/helpers/import-export.js]: 👍

File: addon/mixins/adapters/import-export.js [hunk 2]
```diff
@@ -1,97 +1,16 @@
...
-    });
-
-    return Ember.RSVP.all(promises)
-      .then(function() {
-        // reload from store
-        reloadTypes.forEach(function(type) {
-          store.findAll(type);
-        });
-      });
+    return importData(store, content, options);
```
Comment (fsmanuel) [inline addon/mixins/adapters/import-export.js]: 👍

**Comment by fsmanuel** [comment]
@xn @DanLeiniger @acorncon how are you using the import/export? Via store or adapter? I think about deprecating the use via adapter...

**Comment by xn** [comment]
Store.
